export const GET_OBJECTS_BEGIN = 'GET_OBJECTS_BEGIN';
export const GET_OBJECTS_FAILURE = 'GET_OBJECTS_FAILURE';
export const GET_OBJECTS_SUCCESS = 'GET_OBJECTS_SUCCESS';
export const GRID_VIEW = 'GRID_VIEW';
